#!/usr/bin/env bash
export NVM_DIR=$HOME/.nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
. $NVM_DIR/nvm.sh
nvm install 18
nvm alias default node
nvm use node
npm i -g npm@latest
